# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  exports_version_information:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Export Docker image version information
        run: ./scripts/extract_image_information.sh
      - name: git commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updates prometheus metrics"
          git push 

