# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  exports_version_information:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Export Docker image version information
        run: ./scripts/extract_image_information.sh
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "updates prometheus metrics"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
